# Generated by Django 3.1.12 on 2025-06-01 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20250601_2016'),
    ]

    operations = [
        migrations.AddField(
            model_name='farm',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='farm',
            name='size_unit',
            field=models.CharField(default='acres', max_length=20, verbose_name='Size Unit'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='farm',
            name='size',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Size'),
        ),
    ]
